services:
  - type: web
    name: bnu-cms-api
    plan: starter
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: STATS_PASSWORD
        value: Hanan@1123
    disk:
      name: student-data
      mountPath: /var/data
      sizeGB: 1
